### ISSUE TITLE
Can't connect to pimatic

### ISSUE THREAD

**Issue by HansLackner** [ioBroker/ioBroker.pimatic#3]
Connection to pimatic server "solar-srv" fails, host connection ok, but pimatic failed.
I looked around and found an issue from last year, but that should have been repaired.
Here is the debug code after pimatic reset:

- debug	system.adapter.admin.0: logging true
- debug	redis pmessage io.*.logging io.system.adapter.admin.0.logging {"val":true,"ack":true,"ts":1528283774569,"q":0,"from":"system.adapter.admin.0","lc":1528283774569}
- debug	redis pmessage io.pimatic.0.* io.pimatic.0.info.connection {"val":false,"ack":true,"ts":1528283768146,"q":0,"from":"system.adapter.pimatic.0","lc":1528187888302}
- debug	Connect: http://solar-srv:80/?username=admin&password=xxx
- info	starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.pimatic, node: v8.11.1
- info	States connected to redis: 127.0.0.1:6379
- debug	statesDB connected
- debug	objectDB connected
- info	instance system.adapter.pimatic.0 started with pid 8091

http connection to the pimatic api are working:
http://solar-srv/api/devices -> all connected devices

Thanks for your help

**Comment by HansLackner** [comment]
### For your information this is the solution:
ioBroker.pimatic does not accept the name of the server "solar-srv", the IP "192.168.0.42" works.

**Comment by GermanBluefox** [comment]
We should disable names in I put to avoid future errors

**Comment by GermanBluefox** [comment]
It could be an error of system.  Can you ping from iobroker system solar-srv?

**Comment by HansLackner** [comment]
Sorry for my late answer here, but obviously you did not get my email answer.
On **iobroker-raspi** "ping solar-srv" is not working, while "ssh solar-srv" is working.
On **solar-srv** "ping iobroker-raspi" is working.
On an other **iobroker on Atom** ubuntu "ping solar-srv" is working as well.

**Comment by Apollon77** [comment]
Then you DNS is strange and you need to fix this - or switch to using IPs. Can you try if it works when you directly use IPs?

**Comment by HansLackner** [comment]
IP is working, that why I closed this 6 days before

**Comment by HansLackner** [comment]
Thanks for the DNS hint. I cleared some ARP caches,
Now its working and I will close the topic again.
